app/models.py
from . import db
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Quote:
    """
    Quote class to define Quote Objects"""
    def __init__(self,id,author,quote):
        self.id = id
        self.author = author
        self.quote = quote



class User(UserMixin,db.Model):
    __tablename__="users"
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    image_path = db.Column(db.String(255))
    pass_secure  = db.Column(db.String(255))
    blog = db.relationship("Blog",backref="users",lazy="dynamic")
    comment = db.relationship("Comment",backref="users",lazy="dynamic")

    def save_user(self):
        db.session.add(self)
        db.session.commit()
    def delete_user(self):
        db.session.delete(self)
        db.session.commit()

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
       return f'{self.username}'





class Blog(db.Model):
    __tablename__="blogs"
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(255))
    blog = db.Column(db.String(255))
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_blog(self):
        db.session.add(self)
        db.session.commit()
    def delete_blog(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
       return f'{self.title}'




class Comment(db.Model):
    __tablename__ = "comments"
    id = db.Column(db.Integer,primary_key=True)
    comment = db.Column(db.String(255))
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    blog_id = db.Column(db.Integer,db.ForeignKey("blogs.id"))
    


    def save_comment(self):
        db.session.add(self)
        db.session.commit()
    def delete_comment(self):
        db.session.delete(self)
        db.session.commit()
    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(blog_id=id).all()
        return comments

    def __repr__(self):
       return f'Comment {self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,BooleanField,TextAreaField
from wtforms.validators import InputRequired,Email,EqualTo

class UpdateProfileForm(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [InputRequired()])
    submit = SubmitField('Update')

class UploadBlogForm(FlaskForm):
    title = TextAreaField('Blog Title',validators=[InputRequired()])
    blog =  TextAreaField('your blog',validators=[InputRequired()])
    submit = SubmitField('Post')

class CommentsForm(FlaskForm):
    comment = TextAreaField('Type comment:',validators=[InputRequired()])
    submit = SubmitField('Comment')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail



login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

mail = Mail()
bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)

def create_app(config_name):
    #initializing the application
    app = Flask(__name__)

    #setting up the configuration
    app.config.from_object(config_options[config_name])
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    #Initializing Flask Extenstion
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)


    #Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    app.secret_key = 'password'

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    #configure UploadSet
    configure_uploads(app,photos)
    #setting config
    from .requests import configure_request
    configure_request(app)

    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,flash
from . import main
from ..requests import get_quotes
from ..models import User, Blog,Comment
from .forms import UpdateProfileForm,UploadBlogForm,CommentsForm
from .. import db,photos
from flask_login import login_required,current_user



#Views
@main.route("/")
def index():
    #Getting our quotes
    quotes = get_quotes()
    blog = Blog.query.filter_by().all()
    return render_template("index.html",quotes=quotes,blog=blog)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    blogs = Blog.query.filter_by(user_id=current_user.id).all()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user,blogs=blogs)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    form = UpdateProfileForm()
    if user is None:
        abort(404)


    if form.validate_on_submit():
       user.bio = form.bio.data
       db.session.add(user)
       db.session.commit()

       return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
        return redirect(url_for('main.profile',uname=uname))

@main.route('/user/<uname>/upload_blog',methods = ['POST','GET'])
@login_required
def upload_blog(uname):
    user = User.query.filter_by(username = uname ).first()
    form = UploadBlogForm()
    if user is None:
        abort(404)

    if form.validate_on_submit():
        title = form.title.data
        blog = form.blog.data
        user_id = current_user._get_current_object().id

        new_blog_object = Blog(title=title,blog=blog,user_id=user_id)
        new_blog_object.save_blog()

        return redirect(url_for('main.index'))
    return render_template('new_blog.html', form = form)


@main.route('/<int:blog_id>/delete',methods=['POST','GET'])
@login_required
def delete_blog(blog_id):
    blog=Blog.query.get(blog_id)
    if blog.user_id != current_user.id:
        abort(403)
    
    db.session.delete(blog)
    db.session.commit()

    return redirect(url_for('main.profile',uname=current_user.username))


@main.route('/<int:blog_id>/update',methods=['GET','POST'])
@login_required
def update_blog(blog_id):
    form=UploadBlogForm()
    blog=Blog.query.get(blog_id)
    if blog.user_id != current_user.id:
        abort(403)
    if form.validate_on_submit():
        blog.title=form.title.data
        blog.blog=form.blog.data
        db.session.commit()
        flash('Successfully Updated!')
        return redirect(url_for('main.profile',uname=current_user.username))
    elif request.method=='GET':
        form.title.data=blog.title
        form.blog.data=blog.blog
 
    return render_template('update_blog.html',form=form,legend="Update Blog")


@main.route("/comment/<int:blog_id>",methods=["POST","GET"])
@login_required
def comment_blog(blog_id):
    form = CommentsForm()
    blog = Blog.query.get(blog_id)
    all_comments = Comment.get_comments(blog_id)
    if form.validate_on_submit():
        new_comment = form.comment.data
        blog_id = blog_id
        user_id = current_user._get_current_object().id
        comment_object = Comment(comment=new_comment,user_id=user_id,blog_id=blog_id)
        comment_object.save_comment()
        return redirect(url_for(".comment_blog",blog_id=blog_id))
    return render_template("comments.html",comment_form=form,blog=blog,all_comments=all_comments)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/comments.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{%import 'macros.html' as macro %}


{% block content%}
    <h2>{{blog}}</h2>
    {{macro.displayComments(all_comments)}}
    {{wtf.quick_form(comment_form)}}

{% endblock %}

app/templates/fourOWfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS sorry we can't find that page</h1>
{% endblock %}

app/templates/fourowfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS sorry we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{%import 'macros.html' as macro %}

{% block content %}
<!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="style.css"> -->
<figure class="text-center">
    <blockquote class="blockquote">
    <p>{{quotes.quote}}</p>
    </blockquote>
    <figcaption class="blockquote-footer">
        _author: <cite title="Source Title">{{quotes.author}}</cite>
        <p style="text-align: center;"></p>
    </figcaption>    
</figure>
<br>
{{macro.displayBlog(blog)}}
{% endblock %}

app/templates/macros.html
{% macro displayBlog(blog_list)%}
<!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
<link rel="stylesheet" href="style.css"> -->


<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="p-2 text-center" style="margin-right:0cm; background-color: rgb(97, 197, 147); color: #85790e;">
                <strong>BLOGS</strong>
            </h3>
            {% for blog in blog_list %}

            <div class="card col-md-4 m-3" style="width: 75rem;">
                <div class="card-body">
                    <li class="jumbotron " style="padding-left:40px ; list-style-type: none;">
                        <div class="card">
                            <div class="card-body">
                                Title:{{blog.title}}
                                <p> Blog:{{blog.blog}}</p>
                                <p> Posted on:{{blog.posted.strftime('%Y-%m-%d')}}</p>
                                <a href="{{url_for('main.comment_blog',blog_id=blog.id)}}"><button type="button"
                                        class="btn btn-danger">Comments.</button></a><br>
                                {% endfor %}
                            </div>
                        </div>
                    </li>

                </div>

            </div>
        </div>

    </div>
    {% endmacro %}


    {% macro displayComments(comments_list)%}
    {% for comment in comments_list %}
    <p> {{comment.comment}} </p>
    <p>posted by: {{comment.users}}</p>
    {{comment.posted.strftime('%Y-%m-%d')}} <br>

    {%endfor %}

    {% endmacro %}


    {% macro displayUserBlogs(user_blogs)%}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3 class="p-2 text-center"
                    style="margin-right:5cm; background-color: rgb(181, 202, 219); color: #850e4e;">
                    <strong>BLOGS</strong>
                </h3>
                {% for blog in user_blogs %}
                <li class="jumbotron " style="padding-left:40px ; list-style-type: none;">
                    <div class="card">
                        <div class="card-body">
                            <h3>Title: <strong> {{blog.title}}</strong></h3>
                            Blog: <i>{{blog.blog}}</i>
                            <div class="row">
                                <a href="{{url_for('main.update_blog',blog_id=blog.id)}}"><button type="button"
                                        class="btn btn-light">Update Blog</button>
                                </a>

                                <a href="{{url_for('main.delete_blog',blog_id=blog.id)}}"><i class="fa fa-trash fa-2x"
                                        aria-hidden="true"></i></a> <br>
                                {%endfor%}
                            </div>
                        </div>
                </li>
            </div>

        </div>
    </div>

    {% endmacro%}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Blog </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.upload_blog',uname=current_user.username)}}">Upload Blog</a></li>
                {%endif%}
            </ul>
            </div>
        
        
        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
          </ul>
    </div>
</div>

app/templates/new_blog.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8">

{{wtf.quick_form(form)}}

</div>
<div class="col-md-2"></div>
</div>
</div>

{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
    </div>
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}
    
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>

    {{macro.displayUserBlogs(blogs)}}
      {% endif %}
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/update_blog.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8">

{{wtf.quick_form(form)}}

</div>
<div class="col-md-2"></div>
</div>
</div>

{% endblock%}